org.gradle.caching=true
group=io.ballerina.stdlib
version=1.0.0
ballerinaLangVersion=2201.11.0

githubJohnrengelmanShadowVersion=8.1.1
underCouchDownloadVersion=5.4.0
researchgateReleaseVersion=2.8.0
ballerinaGradlePluginVersion=2.0.1
networkNtVersion=1.5.6
jsonixversion=2.4.1
jacksonDatabindVersion=2.15.2

stdlibIoVersion=1.12.0
