[package]
org = "xlib"
name = "jsonschmea.validator"
version = "1.0.0"
authors = ["Ballerina"]
keywords = ["jsonschema", "json"]
repository = "https://github.com/SasinduDilshara/module-ballerina-jsonschema-vdalidator"
distribution = "2201.11.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "jsonschema-vdalidator-native"
version = "1.0.0"
path = "../native/build/libs/jsonschema-validator-native-1.0.0.jar"

[[platform.java17.dependency]]
groupId = "com.networknt"
artifactId = "json-schema-validator"
version = "1.5.6"
path = "./lib/json-schema-validator-1.5.6.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.15.2"
path = "./lib/jackson-databind-2.15.2.jar"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.15.2"
path = "./lib/jackson-core-2.15.2.jar"
